// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repository

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID           uuid.UUID   `json:"id"`
	Firstname    string      `json:"firstname"`
	Othernames   string      `json:"othernames"`
	Email        string      `json:"email"`
	Organization pgtype.Text `json:"organization"`
	Role         pgtype.Text `json:"role"`
	Phone        pgtype.Text `json:"phone"`
	SshKey       pgtype.Text `json:"ssh_key"`
	CreatedAt    time.Time   `json:"created_at"`
	UpdatedAt    time.Time   `json:"updated_at"`
}
